project_id = "ojiubbzcvrgpnsivofrn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.upload-multi-channel-csv]
verify_jwt = true

[functions.audit-report]
verify_jwt = true

[functions.demo-data]
verify_jwt = false