// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojiubbzcvrgpnsivofrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qaXViYnpjdnJncG5zaXZvZnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjYwMzMsImV4cCI6MjA3MTgwMjAzM30.2RxEuL1s3xJufLdyk0pREDIHwHZEDo9vb4R4KHyinqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});